---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# intro2ds4ip

The following are learning resources for my teaching of Intro to Data Science for Investment professionals. 

## Learner Persona 

Muneeza has been working at a large Canadian pension plan for the last 10 years in a variety of roles directly supporting investment management. She garnered a great deal of respect from her colleagues with her expert knowledge of Pivot tables and lookups, however recently she has noticed some of Excels shortcomings when trying to automate a process. This motivated her to attend a meetup where the speaker talked about how R could considerably streamline processes for people working in Excel, freeing up time for them to do deeper dives on their data. She is about to start a project that requires her to automate a very manual process involving many disparate data sources. In addition she would like to demonstrate to her superiors that value lies within the data she is processing. The speaker spoke about, functions and packages and she would like to leverage these features in R to help with her project. Muneeza also has 2 children under the age of 5 who require an immense amount of attention. Her only spare time is the hours between 8PM to 11PM

